services:
  pg-db:
    image: postgres:17
    restart: on-failure:3
    environment:
      - POSTGRES_PASSWORD=hmk9301
      - POSTGRES_USER=kanux
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - pg-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kanux -d postgres']
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 5s
    volumes:
      - pg-data:/var/lib/postgresql/data
    command: ['postgres', '-c', 'listen_addresses=*']
    logging:
      options:
        max-size: '10m'
        max-file: '3'

networks:
  pg-net: {}

volumes:
  pg-data: {}
