name: Deployment Preparation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare-for-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type-check
        run: npm run type-check

      - name: Start PostgreSQL (test DB)
        run: npm run pg:up -- -d

      - name: Wait for PostgreSQL
        run: |
          until docker compose -f docker-compose.postgres.yml exec pg-db pg_isready -U kanux; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Apply migrations to test DB
        run: npm run test:db:push

      - name: Run tests
        run: npm run test -- --run

      - name: Stop PostgreSQL (test DB)
        run: npm run pg:down

      - name: Deploy migrations to production DB
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      - name: Deployment preparation completed
        run: echo "✔ Deployment preparation complete."
